/**
 * encouragement.js
 *
 * Phrases Penny says when Santiago gets an answer right.
 * Curated from a 100-phrase review — 74 kept.
 */

export const ENCOURAGEMENT = [
  "Yes!",
  "Wow!",
  "Yay!",
  "Hooray!",
  "Bingo!",
  "Boom!",
  "Score!",
  "Nice!",
  "Whoa!",
  "Ooh!",
  "Perfect!",
  "Amazing!",
  "Fantastic!",
  "Excellent!",
  "Incredible!",
  "Brilliant!",
  "Outstanding!",
  "Terrific!",
  "Marvelous!",
  "Great job!",
  "Well done!",
  "Good job!",
  "Very good!",
  "So good!",
  "Too good!",
  "Way to go!",
  "Keep going!",
  "Let's go!",
  "You got it!",
  "You did it!",
  "You win!",
  "You nailed it!",
  "You're right!",
  "That's right!",
  "That's correct!",
  "That's it!",
  "You're amazing!",
  "You're a star!",
  "You're so smart!",
  "You're so good!",
  "You're so clever!",
  "You're a champion!",
  "You're a winner!",
  "You're a genius!",
  "You're the best!",
  "I love it!",
  "I love your answer!",
  "That's the right answer!",
  "Exactly right!",
  "One hundred percent!",
  "Gold star for you!",
  "High five!",
  "Beautiful answer!",
  "You're learning fast!",
  "English is easy for you!",
  "Nothing can stop you!",
  "You got it again!",
  "My favorite student!",
  "Too easy for you!",
  "You know English!",
  "You know so much!",
  "Number one!",
  "Wow, Santiago!",
  "You make me smile!",
  "That was perfect!",
  "That was amazing!",
  "That was so good!",
  "That was fast!",
  "That was brilliant!",
  "That was the right answer!",
  "That was easy for you!",
  "That was beautiful!",
  "That was excellent!",
  "That was incredible!",
];
