/**
 * encouragement.js
 *
 * Phrases Penny says when Santiago gets an answer right.
 * Each entry has an English and Spanish version.
 * Curated from a 100-phrase review — 74 kept.
 */

export const ENCOURAGEMENT = [
  { en: "Yes!",                        es: "¡Sí!"                                  },
  { en: "Wow!",                        es: "¡Guau!"                                },
  { en: "Yay!",                        es: "¡Yupi!"                                },
  { en: "Hooray!",                     es: "¡Hurra!"                               },
  { en: "Bingo!",                      es: "¡Bingo!"                               },
  { en: "Boom!",                       es: "¡Boom!"                                },
  { en: "Score!",                      es: "¡Punto!"                               },
  { en: "Nice!",                       es: "¡Genial!"                              },
  { en: "Whoa!",                       es: "¡Vaya!"                                },
  { en: "Ooh!",                        es: "¡Oh!"                                  },
  { en: "Perfect!",                    es: "¡Perfecto!"                            },
  { en: "Amazing!",                    es: "¡Increíble!"                           },
  { en: "Fantastic!",                  es: "¡Fantástico!"                          },
  { en: "Excellent!",                  es: "¡Excelente!"                           },
  { en: "Incredible!",                 es: "¡Increíble!"                           },
  { en: "Brilliant!",                  es: "¡Brillante!"                           },
  { en: "Outstanding!",                es: "¡Sobresaliente!"                       },
  { en: "Terrific!",                   es: "¡Genial!"                              },
  { en: "Marvelous!",                  es: "¡Maravilloso!"                         },
  { en: "Great job!",                  es: "¡Buen trabajo!"                        },
  { en: "Well done!",                  es: "¡Bien hecho!"                          },
  { en: "Good job!",                   es: "¡Buen trabajo!"                        },
  { en: "Very good!",                  es: "¡Muy bien!"                            },
  { en: "So good!",                    es: "¡Muy bien!"                            },
  { en: "Too good!",                   es: "¡Demasiado bueno!"                     },
  { en: "Way to go!",                  es: "¡Así se hace!"                         },
  { en: "Keep going!",                 es: "¡Sigue adelante!"                      },
  { en: "Let's go!",                   es: "¡Vamos!"                               },
  { en: "You got it!",                 es: "¡Lo lograste!"                         },
  { en: "You did it!",                 es: "¡Lo hiciste!"                          },
  { en: "You win!",                    es: "¡Ganaste!"                             },
  { en: "You nailed it!",              es: "¡Lo clavaste!"                         },
  { en: "You're right!",               es: "¡Tienes razón!"                        },
  { en: "That's right!",               es: "¡Eso es!"                              },
  { en: "That's correct!",             es: "¡Correcto!"                            },
  { en: "That's it!",                  es: "¡Eso es!"                              },
  { en: "You're amazing!",             es: "¡Eres increíble!"                      },
  { en: "You're a star!",              es: "¡Eres una estrella!"                   },
  { en: "You're so smart!",            es: "¡Eres muy inteligente!"                },
  { en: "You're so good!",             es: "¡Eres muy bueno!"                      },
  { en: "You're so clever!",           es: "¡Eres muy listo!"                      },
  { en: "You're a champion!",          es: "¡Eres un campeón!"                     },
  { en: "You're a winner!",            es: "¡Eres un ganador!"                     },
  { en: "You're a genius!",            es: "¡Eres un genio!"                       },
  { en: "You're the best!",            es: "¡Eres el mejor!"                       },
  { en: "I love it!",                  es: "¡Me encanta!"                          },
  { en: "I love your answer!",         es: "¡Me encanta tu respuesta!"             },
  { en: "That's the right answer!",    es: "¡Esa es la respuesta correcta!"        },
  { en: "Exactly right!",              es: "¡Exactamente!"                         },
  { en: "One hundred percent!",        es: "¡Cien por ciento!"                     },
  { en: "Gold star for you!",          es: "¡Estrella dorada para ti!"             },
  { en: "High five!",                  es: "¡Choca esos cinco!"                    },
  { en: "Beautiful answer!",           es: "¡Qué bonita respuesta!"                },
  { en: "You're learning fast!",       es: "¡Estás aprendiendo rápido!"            },
  { en: "English is easy for you!",    es: "¡El inglés es fácil para ti!"          },
  { en: "Nothing can stop you!",       es: "¡Nada te puede detener!"               },
  { en: "You got it again!",           es: "¡Lo lograste de nuevo!"                },
  { en: "My favorite student!",        es: "¡Mi estudiante favorito!"              },
  { en: "Too easy for you!",           es: "¡Demasiado fácil para ti!"             },
  { en: "You know English!",           es: "¡Sabes inglés!"                        },
  { en: "You know so much!",           es: "¡Sabes tanto!"                         },
  { en: "Number one!",                 es: "¡Número uno!"                          },
  { en: "Wow, Santiago!",              es: "¡Guau, Santiago!"                      },
  { en: "You make me smile!",          es: "¡Me haces sonreír!"                    },
  { en: "That was perfect!",           es: "¡Eso fue perfecto!"                    },
  { en: "That was amazing!",           es: "¡Eso fue increíble!"                   },
  { en: "That was so good!",           es: "¡Eso estuvo muy bien!"                 },
  { en: "That was fast!",              es: "¡Eso fue rápido!"                      },
  { en: "That was brilliant!",         es: "¡Eso fue brillante!"                   },
  { en: "That was the right answer!",  es: "¡Esa fue la respuesta correcta!"       },
  { en: "That was easy for you!",      es: "¡Eso fue fácil para ti!"               },
  { en: "That was beautiful!",         es: "¡Eso fue hermoso!"                     },
  { en: "That was excellent!",         es: "¡Eso fue excelente!"                   },
  { en: "That was incredible!",        es: "¡Eso fue increíble!"                   },
];
