/**
 * questions.js — AUTO-GENERATED FROM lessons.js
 *
 * Do not edit this file directly.
 * Add content to lessons.js — this file expands it automatically.
 *
 * Handles three expansion types:
 *   standard — templates × vocab array
 *   family   — templates × members (with role/name/has logic)
 *
 * Each question shape:
 *   id         string    — unique slug
 *   text       string    — the full question Penny asks
 *   topic      string    — parent lesson id
 *   group      string    — parent group label
 *   expects    string    — answer type hint sent to Claude
 *   hint       string|null — specific word/name Claude checks for
 *   acceptAny  string[]|null — multiple valid answers (e.g. aunt has 4 names)
 *   hasPhoto   bool      — true if this question requires an image
 *   photoType  string|null — 'name' (type it) or 'pick' (click one of 6)
 */

import { LESSONS } from './lessons.js';

function slugify(str) {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
}

// ─── Standard expansion (templates × vocab array) ────────────────────────────

function expandStandard(lesson) {
  const questions = [];

  for (const tpl of lesson.templates) {
    if (tpl.text.includes('{word}')) {
      const vocabList = tpl.filterVocab
        ? lesson.vocab.filter(w => tpl.filterVocab.includes(w))
        : lesson.vocab;
      for (const word of vocabList) {
        questions.push({
          id:        `${lesson.id}__${slugify(tpl.text)}__${slugify(word)}`,
          text:      tpl.text.replace(/{word}/g, word),
          topic:     lesson.id,
          group:     lesson.group,
          expects:   tpl.expects,
          hint:      tpl.hint?.replace(/{word}/g, word) ?? null,
          acceptAny: null,
          hasPhoto:  tpl.expects === 'photo-name' || tpl.expects === 'photo-pick',
          photoType: tpl.expects === 'photo-name' ? 'name'
                   : tpl.expects === 'photo-pick' ? 'pick'
                   : null,
        });
      }
    } else {
      // No {word} — one question, no vocab substitution
      // For photo-name questions, one question is generated per vocab word
      // (each word gets its own photo to identify)
      if (tpl.expects === 'photo-name') {
        for (const word of lesson.vocab) {
          questions.push({
            id:        `${lesson.id}__${slugify(tpl.text)}__${slugify(word)}`,
            text:      tpl.text,
            topic:     lesson.id,
            group:     lesson.group,
            expects:   tpl.expects,
            hint:      word,         // Claude checks for this word in Santiago's answer
            acceptAny: null,
            hasPhoto:  true,
            photoType: 'name',
          });
        }
      } else {
        questions.push({
          id:        `${lesson.id}__${slugify(tpl.text)}`,
          text:      tpl.text,
          topic:     lesson.id,
          group:     lesson.group,
          expects:   tpl.expects,
          hint:      null,
          acceptAny: null,
          hasPhoto:  false,
          photoType: null,
        });
      }
    }
  }

  return questions;
}

// ─── Family expansion ────────────────────────────────────────────────────────

function expandFamily(lesson) {
  const questions = [];

  for (const tpl of lesson.templates) {
    for (const member of lesson.members) {

      if (tpl.text.includes('{name}')) {
        // "Is {name} your {role}?" and "What is the name of your {role}?"
        // Skip members that don't exist
        if (!member.has) continue;

        if (tpl.expects === 'name' && member.names.length > 1) {
          // "What is the name of your aunt?" — skip when there are multiple valid names.
          // Use "Is {name} your {role}?" instead (generated below).
          continue;
        }

        // Generate one question per name — handles both single and multiple names.
        // e.g. "Is Natalie your aunt?", "Is Valentina your aunt?", etc.
        for (const name of member.names) {
          const text = tpl.text
            .replace(/{name}/g, name)
            .replace(/{role}/g, member.role);

          questions.push({
            id:        `${lesson.id}__${slugify(tpl.text)}__${slugify(member.role)}__${slugify(name)}`,
            text,
            topic:     lesson.id,
            group:     lesson.group,
            expects:   tpl.expects,
            hint:      tpl.hint?.replace(/{name}/g, name).replace(/{role}/g, member.role) ?? null,
            acceptAny: null,
            hasPhoto:  false,
            photoType: null,
          });
        }

      } else if (tpl.text.includes('{role}')) {
        // "Do you have a {role}?" — generated for ALL members including has: false
        const text = tpl.text.replace(/{role}/g, member.role);
        const hint = tpl.hint === '{has}' ? (member.has ? 'yes' : 'no') : tpl.hint;

        questions.push({
          id:        `${lesson.id}__${slugify(tpl.text)}__${slugify(member.role)}`,
          text,
          topic:     lesson.id,
          group:     lesson.group,
          expects:   tpl.expects,
          hint,
          acceptAny: null,
          hasPhoto:  false,
          photoType: null,
        });
      }
    }
  }

  return questions;
}

// ─── Sequence expansion (days/months before/after) ───────────────────────────

function expandSequence(lesson) {
  const questions = [];

  for (const tpl of lesson.templates) {

    if (tpl.expects === 'current-day' || tpl.expects === 'current-month') {
      // Single question, no substitution — Claude knows today's real date
      questions.push({
        id:        `${lesson.id}__${slugify(tpl.text)}`,
        text:      tpl.text,
        topic:     lesson.id,
        group:     lesson.group,
        expects:   tpl.expects,
        hint:      null,
        acceptAny: null,
        hasPhoto:  false,
        photoType: null,
      });
      continue;
    }

    // before/after questions — expand over the sequence array
    const items = lesson[tpl.seq]; // e.g. lesson.days or lesson.months
    for (let i = 0; i < items.length; i++) {
      const word   = items[i];
      const before = items[(i - 1 + items.length) % items.length];
      const after  = items[(i + 1) % items.length];
      const hint   = tpl.dir === 'after' ? after : before;
      const text   = tpl.text
        .replace('{day}',   word)
        .replace('{month}', word);

      questions.push({
        id:        `${lesson.id}__${slugify(tpl.text)}__${slugify(word)}`,
        text,
        topic:     lesson.id,
        group:     lesson.group,
        expects:   tpl.expects,
        hint,
        acceptAny: null,
        hasPhoto:  false,
        photoType: null,
      });
    }
  }

  return questions;
}

// ─── Main expansion ──────────────────────────────────────────────────────────

function expandLessons(lessons) {
  return lessons.flatMap(lesson =>
    lesson.type === 'family'   ? expandFamily(lesson)   :
    lesson.type === 'sequence' ? expandSequence(lesson) :
                                 expandStandard(lesson)
  );
}

export const QUESTIONS = expandLessons(LESSONS);
