export const TRIP_START = '2026-06-26'
export const TRIP_END   = '2026-07-16'

export const SEGMENTS = [
  {
    id: 'jun26',
    date: '2026-06-26',
    dateLabel: 'Fri Jun 26',
    phase: 'travel',
    icon: '✈️',
    title: 'Travel Day: Daytona to LAX → Santa Monica → LAX to Tahiti',
    events: [
      { icon: '✈️', label: 'Flight Daytona → LAX', detail: 'Southwest — Daytona (9:00am) to LAX (10:30am local)\nConfirmation — Chris: APU2ZX · Natalie: APVVJJ' },
      { icon: '🏖️', label: 'Day in Santa Monica', detail: 'Afternoon to explore Santa Monica — beach, Third Street Promenade, dinner before the flight.' },
      { icon: '🌙', label: 'Flight LAX → Tahiti', detail: 'Air Tahiti Nui Flight QF3816\nLAX (11:00pm) to Papeete (4:10am +1), 8hr 10min\nEconomy — seats not pre-selected\n\nBaggage: 32kg checked + 10kg cabin bag + personal item (each person)\n\nAir Tahiti Reference: APIJMW — manage at airtahiti.com\nBudgetAir Booking: BUSA-35392403' },
    ],
  },
  {
    id: 'jun27',
    date: '2026-06-27',
    dateLabel: 'Sat Jun 27',
    phase: 'polynesia',
    icon: '🌺',
    title: 'Arrive Tahiti → Explore Tahiti by Car → Moorea Night 1',
    events: [
      { icon: '🚗', label: 'Arrive Tahiti & Explore by Car', detail: 'Land ~4:10am\nAvis rental car pickup 5:00am at Faaa Airport\nInternational Driver\'s License required\n\nCar stays parked in Papeete during Moorea week\nReturn: Jul 3 by 5:00pm at Papeete Downtown' },
      { icon: '⛴️', label: 'Ferry to Moorea — Check into Airbnb', detail: 'Ferry: Papeete → Moorea (Aremiti or Terevau, ~30–45 min)\nReserve round-trip tickets in advance\n\nAirbnb: Pk0 Moorea Chill and Beach Lodge\nMoorea-Maiao, Îles du Vent 98728, French Polynesia\nWiFi: MCNBL\nPassword: Mooreachillteihotu200389' },
    ],
  },
  {
    id: 'jun28',
    date: '2026-06-28',
    dateLabel: 'Sun Jun 28',
    phase: 'polynesia',
    icon: '🏝️',
    title: 'Moorea — Day 2',
    summary: 'Full day in Moorea.',
    details: '',
  },
  {
    id: 'jun29',
    date: '2026-06-29',
    dateLabel: 'Mon Jun 29',
    phase: 'polynesia',
    icon: '🏝️',
    title: 'Moorea — Day 3',
    summary: 'Full day in Moorea.',
    details: '',
  },
  {
    id: 'jun30',
    date: '2026-06-30',
    dateLabel: 'Tue Jun 30',
    phase: 'polynesia',
    icon: '🏝️',
    title: 'Moorea — Day 4',
    summary: 'Full day in Moorea.',
    details: '',
  },
  {
    id: 'jul01',
    date: '2026-07-01',
    dateLabel: 'Wed Jul 1',
    phase: 'polynesia',
    icon: '🏝️',
    title: 'Moorea — Day 5',
    summary: 'Full day in Moorea.',
    details: '',
  },
  {
    id: 'jul02',
    date: '2026-07-02',
    dateLabel: 'Thu Jul 2',
    phase: 'polynesia',
    icon: '🏝️',
    title: 'Moorea — Day 6',
    summary: 'Full day in Moorea.',
    details: '',
  },
  {
    id: 'jul03',
    date: '2026-07-03',
    dateLabel: 'Fri Jul 3',
    phase: 'cruise',
    icon: '🚢',
    title: 'Check Out → Explore Tahiti by Car → Board Cruise',
    events: [
      { icon: '🏠', label: 'Check Out of Moorea Airbnb', detail: 'Pack up and check out\nTake the morning ferry back to Papeete\nReturn Avis rental car by 5:00pm at Papeete Downtown' },
      { icon: '🌺', label: 'Spend the Day in Tahiti', detail: 'Final afternoon in French Polynesia — explore Papeete, grab a last local meal, pick up souvenirs.' },
      { icon: '🚢', label: 'Board Norwegian Spirit (10pm)', detail: 'Norwegian Spirit — NCL Cruise\nReservation #65199096\nEmbarkation at 10:00pm in Papeete' },
    ],
  },
  {
    id: 'jul04',
    date: '2026-07-04',
    dateLabel: 'Sat Jul 4',
    phase: 'cruise',
    icon: '🚢',
    title: 'Cruise Day 2 — Moorea',
    summary: 'In port 7:00am – 8:00pm. Likely no excursion — already spent a week here.',
    details: "Port day in Moorea from the cruise ship. In port 7:00am–8:00pm. Already spent a week here — likely won't book a separate excursion. Explore independently or relax onboard.",
  },
  {
    id: 'jul05',
    date: '2026-07-05',
    dateLabel: 'Sun Jul 5',
    phase: 'cruise',
    icon: '🚢',
    title: 'Cruise Day 3 — Raiatea',
    summary: 'In port 7:00am – 8:00pm. Need to book excursion.',
    details: 'Port day in Raiatea. In port 7:00am – 8:00pm. Need to decide on and book an excursion.',
  },
  {
    id: 'jul06',
    date: '2026-07-06',
    dateLabel: 'Mon Jul 6',
    phase: 'cruise',
    icon: '⭐',
    title: 'Cruise Day 4 — Bora Bora',
    summary: 'In port 7:00am – 7:00pm. Need to book excursion.',
    details: 'Port day in Bora Bora — the crown jewel of French Polynesia. In port 7:00am – 7:00pm. Need to decide on and book an excursion (lagoon tour, shark/ray snorkel, overwater bungalow visit, etc.).',
  },
  {
    id: 'jul07',
    date: '2026-07-07',
    dateLabel: 'Tue Jul 7',
    phase: 'cruise',
    icon: '🌊',
    title: 'Cruise Day 5 — Day at Sea',
    summary: 'Day at sea heading toward Hawaii.',
    details: '',
  },
  {
    id: 'jul08',
    date: '2026-07-08',
    dateLabel: 'Wed Jul 8',
    phase: 'cruise',
    icon: '🌊',
    title: 'Cruise Day 6 — Day at Sea',
    summary: 'Day at sea.',
    details: '',
  },
  {
    id: 'jul09',
    date: '2026-07-09',
    dateLabel: 'Thu Jul 9',
    phase: 'cruise',
    icon: '🌊',
    title: 'Cruise Day 7 — Day at Sea',
    summary: 'Day at sea.',
    details: '',
  },
  {
    id: 'jul10',
    date: '2026-07-10',
    dateLabel: 'Fri Jul 10',
    phase: 'cruise',
    icon: '🌊',
    title: 'Cruise Day 8 — Day at Sea',
    summary: 'Day at sea.',
    details: '',
  },
  {
    id: 'jul11',
    date: '2026-07-11',
    dateLabel: 'Sat Jul 11',
    phase: 'cruise',
    icon: '🌊',
    title: 'Cruise Day 9 — Day at Sea',
    summary: 'Day at sea.',
    details: '',
  },
  {
    id: 'jul12',
    date: '2026-07-12',
    dateLabel: 'Sun Jul 12',
    phase: 'cruise',
    icon: '🌋',
    title: 'Cruise Day 10 — Hilo, Big Island',
    summary: 'In port 7:00am – 4:00pm. Secrets of Puna — $310 · 6.5hrs. Walk Kilauea\'s 2018 lava flows with NPS-certified guide.',
    details: 'Secrets of Puna ($310 / 6.5 hrs) — Walk Kilauea\'s most recent 2018 lava flows along the East Rift Zone with a National Park Service certified guide covering volcanology, geology, and history. Stops include MacKenzie State Recreation Area with 40-foot lava walls, Isaac Hale Beach Park miraculously spared by lava flows, and black sand beaches. You\'re walking ON recent lava flows with an NPS certified expert — not the volcano crater itself but the aftermath of the catastrophic 2018 eruption.',
  },
  {
    id: 'jul13',
    date: '2026-07-13',
    dateLabel: 'Mon Jul 13',
    phase: 'cruise',
    icon: '🌿',
    title: 'Cruise Day 11 — Kauai',
    summary: 'In port 8:30am – 5:00pm. Need to book excursion.',
    details: 'Port day in Kauai — the Garden Isle. In port 8:30am – 5:00pm. Need to decide on and book an excursion (Na Pali Coast, Waimea Canyon, helicopter tour, etc.).',
  },
  {
    id: 'jul14',
    date: '2026-07-14',
    dateLabel: 'Tue Jul 14',
    phase: 'cruise',
    icon: '🏄',
    title: 'Cruise Day 12 — Maui',
    summary: 'In port 8:00am – 5:00pm. Need to book excursion.',
    details: 'Port day in Maui. In port 8:00am – 5:00pm. Need to decide on and book an excursion (Road to Hana, snorkeling Molokini, whale watching, etc.).',
  },
  {
    id: 'jul15',
    date: '2026-07-15',
    dateLabel: 'Wed Jul 15',
    phase: 'travel',
    icon: '✈️',
    title: 'Cruise Day 13 — Honolulu → Fly Home at Night',
    events: [
      { icon: '🌺', label: 'Grand Circle Island Tour with Airport Dropoff', detail: 'Ship arrives Honolulu 6:00am\nNCL excursion — full circle island tour of Oahu\nEnds with airport dropoff' },
      { icon: '✈️', label: 'Night Flight Hawaii → Home', detail: 'Southwest departs Honolulu 9:00pm\nConfirmation — Chris: ARERNI · Natalie: ARFWVR\n\nConnects Phoenix (PHX)\nArrives PHX 5:55am → Departs 7:55am → Lands home 3:15pm' },
    ],
  },
  {
    id: 'jul16',
    date: '2026-07-16',
    dateLabel: 'Thu Jul 16',
    phase: 'travel',
    icon: '🏠',
    title: 'Land in MCO — Home',
    summary: 'Arrive back in Orlando. Home by 3pm.',
    details: 'Land at MCO. Home by approximately 3:00pm. Trip complete.',
  },
]
