export const TRIP_START = '2026-06-26'
export const TRIP_END   = '2026-07-15'

export const SEGMENTS = [
  {
    id: 'jun26',
    date: '2026-06-26',
    dateLabel: 'Fri Jun 26',
    phase: 'travel',
    icon: '✈️',
    title: 'Travel Day — Daytona to LA',
    summary: 'Southwest 9am → LAX 10:30am. Day in Santa Monica. Overnight flight LAX → Papeete.',
    details: 'Southwest departs 9:00am, arrives LAX 10:30am. Spend the day in Santa Monica. Overnight flight: LAX to Papeete, Tahiti departs 11:00pm — arrives ~4:00am. Budget $800+ for bag fees.',
  },
  {
    id: 'jun27',
    date: '2026-06-27',
    dateLabel: 'Sat Jun 27',
    phase: 'polynesia',
    icon: '🌺',
    title: 'Arrive Tahiti → Moorea Night 1',
    summary: 'Land ~4am. Car rental. Explore Tahiti by sunrise. Ferry to Moorea.',
    details: 'Arrive Papeete ~4:00am. Pick up rental car at airport. Explore Tahiti by car from sunrise through afternoon. Take the ferry to Moorea — reserve round trip in advance (Aremiti or Terevau ferry).',
  },
  {
    id: 'jun28',
    date: '2026-06-28',
    dateLabel: 'Sun Jun 28',
    phase: 'polynesia',
    icon: '🏝️',
    title: 'Moorea — Day 2',
    summary: 'Full day in Moorea.',
    details: '',
  },
  {
    id: 'jun29',
    date: '2026-06-29',
    dateLabel: 'Mon Jun 29',
    phase: 'polynesia',
    icon: '🏝️',
    title: 'Moorea — Day 3',
    summary: 'Full day in Moorea.',
    details: '',
  },
  {
    id: 'jun30',
    date: '2026-06-30',
    dateLabel: 'Tue Jun 30',
    phase: 'polynesia',
    icon: '🏝️',
    title: 'Moorea — Day 4',
    summary: 'Full day in Moorea.',
    details: '',
  },
  {
    id: 'jul01',
    date: '2026-07-01',
    dateLabel: 'Wed Jul 1',
    phase: 'polynesia',
    icon: '🏝️',
    title: 'Moorea — Day 5',
    summary: 'Full day in Moorea.',
    details: '',
  },
  {
    id: 'jul02',
    date: '2026-07-02',
    dateLabel: 'Thu Jul 2',
    phase: 'polynesia',
    icon: '🏝️',
    title: 'Moorea — Day 6',
    summary: 'Full day in Moorea.',
    details: '',
  },
  {
    id: 'jul03',
    date: '2026-07-03',
    dateLabel: 'Fri Jul 3',
    phase: 'cruise',
    icon: '🚢',
    title: 'Cruise Day 1 — Papeete, Tahiti',
    summary: 'Morning ferry back to Tahiti. Explore by car. Board NCL cruise at 10pm.',
    details: 'Take the morning ferry from Moorea back to Tahiti. Explore Papeete and surrounding area by car one last time. NCL cruise boards later — 10pm debarkation.',
  },
  {
    id: 'jul04',
    date: '2026-07-04',
    dateLabel: 'Sat Jul 4',
    phase: 'cruise',
    icon: '🚢',
    title: 'Cruise Day 2 — Moorea (from ship)',
    summary: 'Port day in Moorea. Likely no excursion booked.',
    details: "Port day in Moorea from the cruise ship. Already spent a week here — likely won't book a separate excursion. Explore independently or relax onboard.",
  },
  {
    id: 'jul05',
    date: '2026-07-05',
    dateLabel: 'Sun Jul 5',
    phase: 'cruise',
    icon: '🚢',
    title: 'Cruise Day 3 — Raiatea',
    summary: 'Port day in Raiatea. Need to book excursion.',
    details: 'Port day in Raiatea. Need to decide on and book an excursion.',
  },
  {
    id: 'jul06',
    date: '2026-07-06',
    dateLabel: 'Mon Jul 6',
    phase: 'cruise',
    icon: '⭐',
    title: 'Cruise Day 4 — Bora Bora',
    summary: 'Bora Bora! Need to book excursion.',
    details: 'Port day in Bora Bora — the crown jewel of French Polynesia. Need to decide on and book an excursion (lagoon tour, shark/ray snorkel, overwater bungalow visit, etc.).',
  },
  {
    id: 'jul07',
    date: '2026-07-07',
    dateLabel: 'Tue Jul 7',
    phase: 'cruise',
    icon: '🌊',
    title: 'Cruise Day 5 — Day at Sea',
    summary: 'Day at sea heading toward Hawaii.',
    details: '',
  },
  {
    id: 'jul08',
    date: '2026-07-08',
    dateLabel: 'Wed Jul 8',
    phase: 'cruise',
    icon: '🌊',
    title: 'Cruise Day 6 — Day at Sea',
    summary: 'Day at sea.',
    details: '',
  },
  {
    id: 'jul09',
    date: '2026-07-09',
    dateLabel: 'Thu Jul 9',
    phase: 'cruise',
    icon: '🌊',
    title: 'Cruise Day 7 — Day at Sea',
    summary: 'Day at sea.',
    details: '',
  },
  {
    id: 'jul10',
    date: '2026-07-10',
    dateLabel: 'Fri Jul 10',
    phase: 'cruise',
    icon: '🌊',
    title: 'Cruise Day 8 — Day at Sea',
    summary: 'Day at sea.',
    details: '',
  },
  {
    id: 'jul11',
    date: '2026-07-11',
    dateLabel: 'Sat Jul 11',
    phase: 'cruise',
    icon: '🌊',
    title: 'Cruise Day 9 — Day at Sea',
    summary: 'Day at sea.',
    details: '',
  },
  {
    id: 'jul12',
    date: '2026-07-12',
    dateLabel: 'Sun Jul 12',
    phase: 'hawaii',
    icon: '🌋',
    title: 'Cruise Day 10 — Hilo, Big Island',
    summary: 'Port day in Hilo. Need to book excursion.',
    details: 'Port day in Hilo, Big Island. Need to decide on and book an excursion (Hawaii Volcanoes National Park, black sand beaches, waterfalls, etc.).',
  },
  {
    id: 'jul13',
    date: '2026-07-13',
    dateLabel: 'Mon Jul 13',
    phase: 'hawaii',
    icon: '🌿',
    title: 'Cruise Day 11 — Kauai',
    summary: 'Port day in Kauai. Need to book excursion.',
    details: 'Port day in Kauai — the Garden Isle. Need to decide on and book an excursion (Na Pali Coast, Waimea Canyon, helicopter tour, etc.).',
  },
  {
    id: 'jul14',
    date: '2026-07-14',
    dateLabel: 'Tue Jul 14',
    phase: 'hawaii',
    icon: '🏄',
    title: 'Cruise Day 12 — Maui',
    summary: 'Port day in Maui. Need to book excursion.',
    details: 'Port day in Maui. Need to decide on and book an excursion (Road to Hana, snorkeling Molokini, whale watching, etc.).',
  },
  {
    id: 'jul15',
    date: '2026-07-15',
    dateLabel: 'Wed Jul 15',
    phase: 'travel',
    icon: '✈️',
    title: 'Cruise Day 13 — Honolulu → Home',
    summary: 'Final port: Honolulu. NCL Oahu excursion with airport drop. Southwest 9pm home.',
    details: 'Final port day in Honolulu. NCL Oahu Excursion includes airport drop — book through NCL. Southwest flight home departs 9:00pm.',
  },
]
